export enum RideStatus {
  SEARCHING_DRIVER = 'SEARCHING_DRIVER',
  DRIVER_FOUND = 'DRIVER_FOUND',
  DRIVER_ARRIVING = 'DRIVER_ARRIVING',
  ONGOING = 'ONGOING',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}
