export enum RideStatus {
  SEARCHING_DRIVER = 'SEARCHING_DRIVER',
  DRIVER_FOUND = 'DRIVER_FOUND',
  DRIVER_ARRIVIED = 'DRIVER_ARRIVIED',
  PAYMENT_PENDING = 'PAYMENT_PENDING',
  ONGOING = 'ONGOING',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}
